# Generated by Django 5.0.2 on 2024-03-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AGE', models.IntegerField()),
                ('image', models.ImageField(upload_to='templates/images')),
                ('CGPA', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.BigIntegerField()),
                ('duration_field', models.DurationField()),
                ('birthday', models.DateTimeField()),
                ('Application_date', models.DateField()),
                ('file_field', models.FileField(upload_to='templates/images')),
                ('rating', models.SmallIntegerField()),
                ('NAME', models.CharField(max_length=20)),
            ],
        ),
    ]
